### ISSUE TITLE
Handle errors

### ISSUE THREAD

**Issue by Art3mK** [Art3mK/youtube-podcasts#2]
START RequestId: 92fba71c-8517-5af3-bada-f16d205999aa Version: $LATEST
15:30:25
{'videoId': 'sp3GmS5toFo', 'title': '30 000 подписанных книг или лысина? Задай вопрос Оскару! Закажи книгу на justfuckingdoit.ru', 'channel_title': 'Оскар Хартманн', 'publishedDate': '2019-12-15T07:23:35.000Z'}
15:30:25
[youtube] sp3GmS5toFo: Downloading webpage
15:30:26
[youtube] sp3GmS5toFo: Downloading video info webpage
15:30:27
ERROR: This video is unavailable.
15:30:27
[ERROR] DownloadError: ERROR: This video is unavailable. Traceback (most recent call last):   File "/var/task/audio_uploader.py", line 76, in lambda_handler     download_audio_file(data['videoId'])   File "/var/task/audio_uploader.py", line 16, in download_audio_file     ydl.download([url])   File "/var/task/youtube_dl/YoutubeDL.py", line 2018, in download     url, force_generic_extractor=self.par
15:30:27
END RequestId: 92fba71c-8517-5af3-bada-f16d205999aa
15:30:27
REPORT RequestId: 92fba71c-8517-5af3-bada-f16d205999aa Duration: 1538.52 ms Billed Duration: 1600 ms Memory Size: 256 MB Max Memory Used: 116 MB

**Comment by Art3mK** [comment]
hBACz_OP2LU
